# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_native
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_native)
  gltfLoader_config = debug_native
endif
ifeq ($(config),debug_x64)
  gltfLoader_config = debug_x64
endif
ifeq ($(config),debug_x32)
  gltfLoader_config = debug_x32
endif
ifeq ($(config),release_native)
  gltfLoader_config = release_native
endif
ifeq ($(config),release_x64)
  gltfLoader_config = release_x64
endif
ifeq ($(config),release_x32)
  gltfLoader_config = release_x32
endif

PROJECTS := gltfLoader

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

gltfLoader:
ifneq (,$(gltfLoader_config))
	@echo "==== Building gltfLoader ($(gltfLoader_config)) ===="
	@${MAKE} --no-print-directory -C . -f gltfLoader.make config=$(gltfLoader_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f gltfLoader.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_native"
	@echo "  debug_x64"
	@echo "  debug_x32"
	@echo "  release_native"
	@echo "  release_x64"
	@echo "  release_x32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gltfLoader"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"